### PR TITLE
allow datadecoder can be used outside file. Check if it's webp format.

### PR DESCRIPTION
**Pull request by systembugtj**

### CODE REVIEW

**Comment by ryokosuge** [comment]
@systembugtj Thank you for taking out the Pull Request!
The target of Test was misaligned, please correct it.

### WebPDecodeTests.swift

Since the file `WebPDecodeTests.swift` was also included in `Nuke - WebP - Plugin iOS`, please remove it from the target.

When introduced in the image...

before:



after:



### sample.gif

Similarly, since the file `sample.gif` is contained in `Nuke - WebP - Plugin iOS` and it is not included in `Nuke - WebP - Plugin Tests iOS`, please modify it as well.

When introduced in the image...

before:



after:

**Comment by ryokosuge** [comment]
After correcting the above 2 points, I passed the test, so thank you!

**Comment by systembugtj** [comment]
Thanks very much for the guidance, that's very helpful. :) I didn't have experiecen on pods before. That's good lesson. :)

**Comment by ryokosuge** [comment]
@systembugtj Thank you for a wonderful pull request!

**Pull request merged**
